apiVersion: couchbase.btburnett.com/v1beta1
kind: CouchbaseIndexSet
metadata:
  name: couchbaseindexset-sample
spec:
  cluster: 
    clusterRef:
      name: cb-example # name of the CouchbaseCluster resource in Kubernetes
  bucketName: default
  indices:
  - name: example
    indexKey:
    - type
    - id
    numReplicas: 0
  - name: example2
    scopeName: my_scope
    collectionName: my_collection
    indexKey:
    - type
    - name
    - id
    partition:
      expressions:
      - meta().id
