name: CI

on:
  push:
    tags:
      - release/*
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "VERSION=${GITHUB_REF/refs\/tags\/release\//}" >> $GITHUB_ENV
        if: ${{ startsWith(github.ref, 'refs/tags/release/') }}
      - run: echo "VERSION=PR-${{github.event.number}}" >> $GITHUB_ENV
        if: ${{ !startsWith(github.ref, 'refs/tags/release/') }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        if: ${{ !github.event.pull_request.head.repo.fork }}
        run: make docker-build docker-push IMG=ghcr.io/brantburnett/couchbase-index-operator:${{ env.VERSION }}
      - name: Build
        if: ${{ github.event.pull_request.head.repo.fork }}
        run: make docker-build IMG=ghcr.io/brantburnett/couchbase-index-operator:${{ env.VERSION }}
